language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm run coverage
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change